DB schema vertinimui
Erikas/Messenger pull request #1
Opened 2024-03-16 15:00 UTC by imila254

Laukiu komentaru ir pastebejimu. Nesu tikra del tos thread/thead-group dalies

2024-03-18 11:35 UTC, Erikas requested changes
1.  Stenkis, kad būtų aišku kokios lentos yra pvz. Nėra aišku, kad picture_ID yra attachment_Id.
2. Jeigu gerai suprantu, tai sumaišyti ryšiai tarp lentų? ThreadGroupas gali turėti daug threadų, bet čia padarytą atvirkščiai?

2024-03-18 15:44 UTC, imila254 commented
Įkėliau atnaujintą versiją.
1. Turi omeny, kad būtų atskira Pictures lenta ar tiesiog pervadint picture_Id į tokį, kuris leistų lengviau suprast, kad tai yra attachment? (padariau pakeitimus pagal antrą variantą)
2. Bet dabar ir yra padaryta, kad ThreadGroup turi daug thead_id's (thread_id integer [ref: < Thread.id]) ir Thread turi daug ThreadGroup's ( thread_group_id integer [ref: < ThreadGroup.id]). Ar Thread gali turėt tik vieną ThreadGroup?

2024-03-18 18:22 UTC, Erikas commented
> Įkėliau atnaujintą versiją.
> 
> 1. Turi omeny, kad būtų atskira Pictures lenta ar tiesiog pervadint picture_Id į tokį, kuris leistų lengviau suprast, kad tai yra attachment? (padariau pakeitimus pagal antrą variantą)
> 2. Bet dabar ir yra padaryta, kad ThreadGroup turi daug thead_id's (thread_id integer [ref: < Thread.id]) ir Thread turi daug ThreadGroup's ( thread_group_id integer [ref: < ThreadGroup.id]). Ar Thread gali turėt tik vieną ThreadGroup?


Dėl picture gerai kaip padarei. Tiesiog venk  foreign keys neįtraukt tikro name, nes tokiu būdų nukenčia readability. Dabar šiaip išvis pagalvojau, kad jeigu mes galvojam turėti tik vieną profile picture, tai gal tiesiog įsidėkime profilePhotoBloblUrl? Čia šiaip mintis. O dėl antro tai daug ThreadGroup ir Thread many to many does not make sense. įdėja ThreadGroup buvo, kad realiai galėtume sukurti Threade esančių userių  listą. Tokiu būdu turėtume turėti threadą kuriame defininame name, ThreadGroupID (arba pvz ThreadParticipant). Tada pagalvojau panaikinkime MessageId is šitos lentos ir senderAccountId. Vietoj to perkelikime į message lentą ThreadID Sender_Account_Id. Tokiu atvėju Threadas  gali turėti daug messages ir daug parcipants. Ką manai?

2024-03-18 20:41 UTC, imila254 commented
Update. Manau, palieku profile picture attachment lentoje. Joje vis tiek yra time stamp, tai loginimui gal geriau taip turėt.
Dėl threadGroup/Thread/Message pastabų ir komentatų tai sutinku, atsižvelgus į tavo komentarus schema atrodo logiškiau.

2024-03-19 08:54 UTC, Erikas commented
Viskas gerai yra palikti taip su picture attachmentu. Tik problema, kad jeigu norėsi jog message turėtų daug attachmentų, tai reikalaus papildomos lentos. Ir kinda šita tavo attachment lenta virs file lenta. Dabar kaip padarytas ryšys tarp Thread ir ThreadGroup, tai vadinama circular depepdency. Siulyčiau panaikinti threadGroupId is Thread lentos ir palikti tik ThreadGroup lentoje esantį ThreadId. Taip vienas Thread galės turėti daug GroupMemberių.

2024-03-23 13:41 UTC, imila254 commented
schema updated

2024-03-25 05:31 UTC, Erikas commented
gal i threada dedam userAccountId? nes visur naudojam ji, o ten user id? userAccount su threadmembers turetu tureti 1 su daug rysi

2024-03-25 17:29 UTC, imila254 commented
![image](https://github.com/Erikas/Messenger/assets/71584446/a71d93c6-2f36-46c9-a59c-4b21e0e33955)

2024-03-25 18:34 UTC, IevaZemg commented
O šiaip klausimas ar [UserAccoun].[UserId] ir [UserAccount].[UserAccountId] kuo skiriasi? Nes vienose lentose naudoji viena, kitose lentose kita. Ar nesigauna kaip dviguba informacija? Gal čia normali praktika turėti du skirtingus unikalius id vienam objektui? [Message].[MessageContent] siūlyčiau nvarchar.

2024-03-25 18:53 UTC, Erikas commented
![image](https://github.com/Erikas/Messenger/assets/5561591/977150a8-eb78-45ca-b83f-363fa0e000c4)
sito rysio nekeisi?

2024-03-25 19:06 UTC, imila254 commented
Aha, buvo klaida, pataisiau.

2024-03-25 19:25 UTC, Erikas approved these changes

2024-03-25 19:28 UTC, GMurnevaite approved these changes

2024-03-26 19:59 UTC, merged