DB schema
Erikas/Messenger pull request #3
Opened 2024-03-18 20:32 UTC by GMurnevaite

Duombazės schema jūsų vertinimui.

2024-03-18 21:03 UTC, imila254 requested changes
Trūksta rodyklyčių iš Message lentos receiverId ir userId stulpelių. Manau, kad Message lentoje užtektų tik senderId, nes jei tai grupė, tai receiverių gali būti daug ir svarbiausias lieka žinutės siuntėjas. Taip pat, pats žinutės siuntėjas gali būti ir gavėjas (grupės atveju).

2024-03-19 08:32 UTC, Erikas commented
dar gal pridėčiau, kad būtų fun, kad naminguose matytusi lentų pavadinaimai. pvz friendUserId. Taip pat nesuprantu ryšio tarp threadGroup ir Thread. Manau, kad Thread esantis ThreadGroupId yra nereikalingas. ThreadGroup žmonės bus galima rasti pagal ThreadGroup esantį ThreadId. Iš esmės, vienas threadas gali turėti daug threadGroup (participants), bet vienas ThreadGroupas (participant) gali turėti tik veiną threadą. One to many.

2024-03-19 08:43 UTC, Erikas commented
Dar sakyčiau, kad ne thread turėtų turėti messege Id, o Message turėtų turėti threadID. Tada gautusi, kad threadas gali turėti daug message. O dabar gaunasi, Threade bus tik vienas message? Plus kažkaip man atrodo, kad message ir thread ryšys atvaizduotas neiteinsgai, pagal tą ka matau diagramoje? Pagal tai kaip nupiešta, čia gaunasi 1 to 1?

2024-03-19 08:44 UTC, Erikas commented
Tavo atvėju ir UserSettings turėtų būti one to one. O ne one to many?

2024-03-19 08:46 UTC, Erikas commented
Attachment sake. Pas tave ryšys yra one to one. Jeigu nori, kad būtų vienoje žinutėje daug attashcmentų tada turėtų būti messageId attachment lentoje, o ne attachment message lentoje.

2024-03-25 05:21 UTC, Erikas approved these changes

2024-03-25 19:31 UTC, imila254 approved these changes

2024-03-26 20:01 UTC, merged